config/routes.rb
Cnmtsc::Application.routes.draw do

  get "messages/new/:id" => "messages#new", :as => :message_new
  post "messages" => "messages#create", :as => :messages

  get "orders/new/:id" => "orders#new", :as => :order_new
  post "orders" => "orders#create", :as => :orders
  match "profile" => "homes#profile", :as => :profile

  get "homes/index"
  root :to => "homes#index"
  resource :user_session
  match "login" => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'register' => "users#new", :as => :register
  resources :news, :only => [:show,:index]
  resources :products, :only => [:show, :index, :new, :create]
  resources :users, :only => [:new, :create]

  namespace :admin do
    root :to => "main#index"
    
    resources :users do
      collection do
        get "change_password"
        put "update_password"
      end
    end
    resources :news
    resources :products
    match "messages" => "messages#index", :as => "messages"
  end

end

app/views/shared/_footer.html.erb
<div class="foot_alter225">

    <div align="center">

        <a target="_black" href="http://www.qianxun.com/woman.html">

            <span>精致美人</span>

            <strong>优雅与性感共舞</strong>

        </a>

        <a target="_black" href="http://www.qianxun.com/man.html">

            <span>时尚绅士</span>

            <strong>型男之时装殿堂</strong>

        </a>

        <a target="_black" href="http://help.360buy.com/help/question-65.html">

            <span>全场免运费</span>

            <strong>不限金额不限地区</strong>

        </a>

    </div>

</div>

<div style="width: 978px; margin: 15px auto 0pt; font: 12px/25px '';  text-align: center; clear: both;">

    <div><a target="_black" href="http://www.qianxun.com">首页</a>  |  <a target="_black" href="http://www.360buy.com/contact/">联系我们</a>  |  <a target="_black" href="http://www.360buy.com/contact/joinin.aspx">商家入驻</a>  |  <a target="_black" href="http://www.360buy.com/intro/service.aspx">广告服务</a></div>

    <div style=" font-family:Verdana, Arial, Helvetica, sans-serif; padding-bottom:20px">Copyright&copy; 2011 cnmtsc.com All Rights Reserved 沪ICP备09000930号 </div>

</div>

app/views/shared/_header.html.erb
<div class="content">

            <h1 class="logo"><a href="http://www.qianxun.com" title="千寻网">千寻网</a></h1>

            <div class="h_right">

                <ul class="h_menu">

                    <div id="shortcut">

                        <ul>

                          <li class="fore1" id="loginfo">您好！欢迎来到川南煤炭市场网！&nbsp;&nbsp;&nbsp;
                              <span>
                                  <% if current_user == nil %>
                                  <%= link_to "[请登录]", login_url %>，新用户？<%= link_to "[免费注册]", register_url %>
                                <% else %>
                                  用户名:<%= link_to "#{current_user.login}", root_url %>, <%= link_to "[退出]", logout_url %>
                                <% end %>

                              </span></li>

                            <li class="fore2"><%= link_to "我的订单", profile_url %></li>

                            <li><%= link_to "我的空间", profile_url %></li>

                        </ul>

                        <span class="clr"></span>

                    </div>

                </ul>

                <div class="search_div">

                    <form name="search" method="get" action="http://search.qianxun.com/search">

                        <input name="keyword" type="text"  class="search_input" />

                        <input name="" type="submit" class="search_btn" onmouseover="this.className='search_btn_on'" onmouseout="this.className='search_btn'" />

                    </form>

                </div>

                <div class="clr"></div>

                热卖分类：<a href="#" class="f_939393">电煤供应</a>  <a href="#">原煤</a>  <a href="#"class="f_939393">川西北煤炭供应</a>  <a href="">川南煤炭市场企业标志</a> 













            </div>

        </div>

        <div class="clr"></div>

        <div class="nav_bg">

            <div class="content">

                <div class="nav">



                    <ul  class="banner">


                        <%= menu_nav :home do %><%= link_to "首页", root_path() %><% end %>
                        <%= menu_nav :new do %><%= link_to "新闻", news_index_path() %><% end %>
                        <%= menu_nav :product do %><%= link_to "产品", products_path() %><% end %>

                    </ul>



	<input type="hidden" class='bannerv'; value="index" />

                </div>

            </div>

        </div>