config/routes.rb
Cnmtsc::Application.routes.draw do

  get "messages/new/:id" => "messages#new", :as => :message_new
  post "messages" => "messages#create", :as => :messages

  get "orders/new/:id" => "orders#new", :as => :order_new
  post "orders" => "orders#create", :as => :orders
  match "profile" => "homes#profile", :as => :profile

  get "homes/index"
  root :to => "homes#index"
  resource :user_session
  match "login" => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'register' => "users#new", :as => :register
  resources :news, :only => [:show,:index]
  resources :products, :only => [:show, :index, :new, :create]
  resources :users, :only => [:new, :create]

  namespace :admin do
    root :to => "main#index"
    
    resources :users do
      collection do
        get "change_password"
        put "update_password"
      end
    end
    resources :news
    resources :products
    match "messages" => "messages#index", :as => "messages"
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
    has_attached_file :avatar,
    :url  => "/system/products/:id/:style_:basename.:extension",
    :path => ":rails_root/public/system/products/:id/:style_:basename.:extension",
    :styles => { :normal => '160x160#', :thumb => '80x80#',
  },
    :default_style => :normal


  validates_attachment_size :avatar, :less_than => 2.megabytes
  belongs_to :user
  has_many :orders
  has_many :messages
end

app/controllers/admin/products_controller.rb
# To change this template, choose Tools | Templates
# and open the template in the editor.
class Admin::ProductsController < Admin::BaseController
  main_nav_highlight :content
  sec_nav_highlight :products
  def index
    @products = Product.all
  end

  # GET /news/1
  # GET /news/1.xml

  def new
    @product = @user.products.new
  end

  # GET /news/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /news
  # POST /news.xml
  def create
    @product = @user.products.new(params[:product])
    @product.save
    flash[:notice] = :create_successful
    redirect_to admin_products_path()
  end

  # PUT /news/1
  # PUT /news/1.xml
  def update
    @product = Product.find(params[:id])
    @product.update_attributes(params[:product])
    flash[:notice] = :update_successful
    redirect_to admin_products_path()
  end

  # DELETE /news/1
  # DELETE /news/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to admin_products_path()
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # GET /news
  # GET /news.xml
  menu_nav_highlight :product
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @news }
    end
  end

  # GET /news/1
  # GET /news/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @news }
    end
  end

  def new
    redirect_to login_path() if current_user == nil
    @product = Product.new
  end

  def create
    @product = current_user.products.new(params[:product])
    @product.verify = false
    @product.safement = false
    @product.save
    flash[:notice] = :create_successful
    redirect_to admin_products_path()
  end


end

app/views/admin/products/_entries.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>


<table>
	<thead>
		<tr>
			<th><%= :verify %></th>
			<th><%= :safement %></th>
			<th><%= :title %></th>
			<th><%= :description %></th>
                        <th><%= :tel %></th>
                        <th><%= :user %></th>
                        <th><%= :avatar %></th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @products.each do |product| %>
		<tr>
			<td><%= product.verify %></td>
			<td><%= product.safement %></td>
			<td><%= product.title %></td>
                        <td><%= product.description %></td>
                        <td><%= product.tel %></td>
                        <td><%= product.user %></td>
			<td><%= image_tag product.avatar(:thumb) %></td>
			<td>
				<%= link_to "edit", edit_admin_product_path(product), :title => :edit, :class => "edit" %>&nbsp;
				<%= link_to "delete", admin_product_path(product), :method => :delete, :confirm => :delete, :title => :delete, :class => "delete" %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/products/_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<%= form.inputs do %>
	<%= form.input :verify, :input_html => { :class => "text-input medium-input" } %>
	<%= form.input :safement, :input_html => { :class => "text-input medium-input" } %>
	<%= form.input :title, :input_html => { :class => "text-input medium-input" } %>
        <%= form.input :description, :input_html => { :class => "text-input medium-input" } %>
        <%= form.input :tel, :input_html => { :class => "text-input medium-input" } %>
        <%= form.input :user, :input_html => { :class => "text-input medium-input" } %>
        <%= form.input :avatar, :as => :file, :hint => "请务必上传艺术家的头像！或者代表图!" %>
<% end %>

<%= form.buttons do %>
	<%= form.commit_button :button_html => { :class => "button" } %>
<% end %>

app/views/admin/products/edit.html.erb
<h3>产品管理</h3>

<ul class="shortcut-buttons-set">
	<li><%= link_to "返回控制面板", admin_root_path(), :class => "shortcut-button home" %></li>
	<li><%= link_to "返回分类列表", admin_products_path(), :class => "shortcut-button episode" %></li>
</ul>

<div class="clear"></div>

<div class="content-box">
	<div class="content-box-header">
		<h3>修改产品</h3>
	</div>

	<div class="content-box-content">
		<%= semantic_form_for(@product, :url => admin_product_path(@product)) do |f| %>
			<%= render :partial => 'form', :object => f %>
		<% end %>
	</div>
</div>

app/views/admin/products/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<h2>产品展示</h2>

<ul class="shortcut-buttons-set">
	<li><%= link_to "返回控制面板", admin_root_path(), :class => "shortcut-button home" %></li>
	<li><%= link_to "添加产品", new_admin_product_path(), :class => "shortcut-button artist" %></li>
</ul>

<div class="clear"></div>

<div class="content-box">
	<div class="content-box-header">
		<h3>产品列表</h3>
	</div>

	<div class="content-box-content">
		<% if @products.blank? %>
			<p>暂无产品,您可以<%= link_to "添加产品", new_admin_product_path() %>！</p>
		<% else %>
			<%= render "entries" %>
		<% end %>
	</div>
</div>

app/views/admin/products/new.html.erb
<h3>产品管理模块</h3>

<ul class="shortcut-buttons-set">
	<li><%= link_to "返回控制面板", admin_root_path(), :class => "shortcut-button home" %></li>
	<li><%= link_to "返回新闻管理列表", admin_products_path(), :class => "shortcut-button user" %></li>
</ul>

<div class="clear"></div>

<div class="content-box">
	<div class="content-box-header">
		<h3>添加新闻</h3>
	</div>

	<div class="content-box-content">
		<%= semantic_form_for(@product, :url => admin_products_path(), :html => { :multipart => true }) do |f| %>
			<%= render :partial => 'form', :object => f %>
		<% end %>
	</div>
</div>