config/routes.rb
Cnmtsc::Application.routes.draw do

  get "messages/new/:id" => "messages#new", :as => :message_new
  post "messages" => "messages#create", :as => :messages

  get "orders/new/:id" => "orders#new", :as => :order_new
  post "orders" => "orders#create", :as => :orders
  match "profile" => "homes#profile", :as => :profile

  get "homes/index"
  root :to => "homes#index"
  resource :user_session
  match "login" => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'register' => "users#new", :as => :register
  resources :news, :only => [:show,:index]
  resources :products, :only => [:show, :index, :new, :create]
  resources :users, :only => [:new, :create]

  namespace :admin do
    root :to => "main#index"
    
    resources :users do
      collection do
        get "change_password"
        put "update_password"
      end
    end
    resources :news
    resources :products
    match "messages" => "messages#index", :as => "messages"
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
    has_attached_file :avatar,
    :url  => "/system/products/:id/:style_:basename.:extension",
    :path => ":rails_root/public/system/products/:id/:style_:basename.:extension",
    :styles => { :normal => '160x160#', :thumb => '80x80#',
  },
    :default_style => :normal


  validates_attachment_size :avatar, :less_than => 2.megabytes
  belongs_to :user
  has_many :orders
  has_many :messages
end

app/controllers/admin/products_controller.rb
# To change this template, choose Tools | Templates
# and open the template in the editor.
class Admin::ProductsController < Admin::BaseController
  main_nav_highlight :content
  sec_nav_highlight :products
  def index
    @products = Product.all
  end

  # GET /news/1
  # GET /news/1.xml

  def new
    @product = @user.products.new
  end

  # GET /news/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /news
  # POST /news.xml
  def create
    @product = @user.products.new(params[:product])
    @product.save
    flash[:notice] = :create_successful
    redirect_to admin_products_path()
  end

  # PUT /news/1
  # PUT /news/1.xml
  def update
    @product = Product.find(params[:id])
    @product.update_attributes(params[:product])
    flash[:notice] = :update_successful
    redirect_to admin_products_path()
  end

  # DELETE /news/1
  # DELETE /news/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to admin_products_path()
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # GET /news
  # GET /news.xml
  menu_nav_highlight :product
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @news }
    end
  end

  # GET /news/1
  # GET /news/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @news }
    end
  end

  def new
    redirect_to login_path() if current_user == nil
    @product = Product.new
  end

  def create
    @product = current_user.products.new(params[:product])
    @product.verify = false
    @product.safement = false
    @product.save
    flash[:notice] = :create_successful
    redirect_to admin_products_path()
  end


end

app/views/products/index.html.erb
<div class="content">
  <div class="pages_leftnav">
    <div class="pages_w_rborder" style="border-bottom:0;width:188px; float:left; margin-top:10px;">
      <h2 class="pages_w_top10">热销排行榜</h2>
      <ul class="pages_w_topul2">

        <li class=""><span>1</span><div class="ulimg"><a href="http://www.qianxun.com/product/335281.html" target="_blank" title=""><img src="http://img11.360buyimg.com/n2/3136/61e194b6-fcde-41c1-9d94-b09e23b71b3a.jpg" width="50" height="50" alt="" onerror="this.src='http://misc.qianxun.com/images/none100.gif'"></a></div><div class="name"><a href="http://www.qianxun.com/product/335281.html" target="_blank" title="">周生生 足金小女巫吊坠 4.37克</a></div>
          <div class="price">
            <img onerror="this.src='http://misc.qianxun.com/images/no2.gif'" src="http://qxprice.360buyimg.com/gp335281,2.png">
          </div>
        </li>

        <li class=""><span>2</span><div class="ulimg"><a href="http://www.qianxun.com/product/1000457905.html" target="_blank" title=""><img src="http://img10.360buyimg.com/n2/5415/510d6775-3627-4a93-bd4d-4aeb5bbf6769.jpg" width="50" height="50" alt="" onerror="this.src='http://misc.qianxun.com/images/none100.gif'"></a></div><div class="name"><a href="http://www.qianxun.com/product/1000457905.html" target="_blank" title="">CROCODILE鳄鱼恤新款男皮带D71306-1 黑色  110</a></div>
          <div class="price">
            <img onerror="this.src='http://misc.qianxun.com/images/no2.gif'" src="http://qxprice.360buyimg.com/gp1000457905,2.png">
          </div>
        </li>

        <li class=""><span>3</span><div class="ulimg"><a href="http://www.qianxun.com/product/1000549485.html" target="_blank" title=""><img src="http://img10.360buyimg.com/n2/7208/0d0b6e9a-59ac-4ca3-bc55-f8e2cdb37e77.jpg" width="50" height="50" alt="" onerror="this.src='http://misc.qianxun.com/images/none100.gif'"></a></div><div class="name"><a href="http://www.qianxun.com/product/1000549485.html" target="_blank" title="">vegoos威古氏女款太阳镜 9001 酒红色</a></div>
          <div class="price">
            <img onerror="this.src='http://misc.qianxun.com/images/no2.gif'" src="http://qxprice.360buyimg.com/gp1000549485,2.png">
          </div>
        </li>

        <li class=""><span>4</span><div class="ulimg"><a href="http://www.qianxun.com/product/203316.html" target="_blank" title=""><img src="http://img11.360buyimg.com/n2/1746/79d9bca9-b065-4eaa-b690-24a70919ac36.jpg" width="50" height="50" alt="" onerror="this.src='http://misc.qianxun.com/images/none100.gif'"></a></div><div class="name"><a href="http://www.qianxun.com/product/203316.html" target="_blank" title="">依波正装系列石英男表239323</a></div>
          <div class="price">
            <img onerror="this.src='http://misc.qianxun.com/images/no2.gif'" src="http://qxprice.360buyimg.com/gp203316,2.png">
          </div>
        </li>

        <li class=""><span>5</span><div class="ulimg"><a href="http://www.qianxun.com/product/384584.html" target="_blank" title=""><img src="http://img14.360buyimg.com/n2/4886/9e5d4820-402f-46e6-9e92-2d5a6d2a4544.jpg" width="50" height="50" alt="" onerror="this.src='http://misc.qianxun.com/images/none100.gif'"></a></div><div class="name"><a href="http://www.qianxun.com/product/384584.html" target="_blank" title="">岱宇SHAKEWEIGHT摇摆铃-男版</a></div>
          <div class="price">
            <img onerror="this.src='http://misc.qianxun.com/images/no2.gif'" src="http://qxprice.360buyimg.com/gp384584,2.png">
          </div>
        </li>

        <li class=""><span>6</span><div class="ulimg"><a href="http://www.qianxun.com/product/1000125540.html" target="_blank" title=""><img src="http://img10.360buyimg.com/n2/5188/67ebf114-6108-402c-939a-7f85c4effa5b.jpg" width="50" height="50" alt="" onerror="this.src='http://misc.qianxun.com/images/none100.gif'"></a></div><div class="name"><a href="http://www.qianxun.com/product/1000125540.html" target="_blank" title="">uiyi佑一良品时尚睿智系列细斜纹男士牛皮长款钱包00521-A09090350 深卡其色</a></div>
          <div class="price">
            <img onerror="this.src='http://misc.qianxun.com/images/no2.gif'" src="http://qxprice.360buyimg.com/gp1000125540,2.png">
          </div>
        </li>

        <li class=""><span>7</span><div class="ulimg"><a href="http://www.qianxun.com/product/1000459540.html" target="_blank" title=""><img src="http://img10.360buyimg.com/n2/7727/01b6be02-8827-4f17-82e2-03fc275ed258.jpg" width="50" height="50" alt="" onerror="this.src='http://misc.qianxun.com/images/none100.gif'"></a></div><div class="name"><a href="http://www.qianxun.com/product/1000459540.html" target="_blank" title="">2011新款依波表（EBOHR）豪华机械系列女装表10500125</a></div>
          <div class="price">
            <img onerror="this.src='http://misc.qianxun.com/images/no2.gif'" src="http://qxprice.360buyimg.com/gp1000459540,2.png">
          </div>
        </li>

        <li class=""><span>8</span><div class="ulimg"><a href="http://www.qianxun.com/product/1000161597.html" target="_blank" title=""><img src="http://img12.360buyimg.com/n2/5547/91d7a954-ef94-41b3-84d9-0bbecae6e64b.jpg" width="50" height="50" alt="" onerror="this.src='http://misc.qianxun.com/images/none100.gif'"></a></div><div class="name"><a href="http://www.qianxun.com/product/1000161597.html" target="_blank" title="">vegoos威古氏偏光太阳镜8011枪色</a></div>
          <div class="price">
            <img onerror="this.src='http://misc.qianxun.com/images/no2.gif'" src="http://qxprice.360buyimg.com/gp1000161597,2.png">
          </div>
        </li>

        <li class=""><span>9</span><div class="ulimg"><a href="http://www.qianxun.com/product/1000567419.html" target="_blank" title=""><img src="http://img14.360buyimg.com/n2/6868/93faf521-45a0-4b75-b361-f793f1a458bd.jpg" width="50" height="50" alt="" onerror="this.src='http://misc.qianxun.com/images/none100.gif'"></a></div><div class="name"><a href="http://www.qianxun.com/product/1000567419.html" target="_blank" title="">CROCODILE2011鳄鱼恤时尚轻巧男钱包BYD341046-403啡色  横款</a></div>
          <div class="price">
            <img onerror="this.src='http://misc.qianxun.com/images/no2.gif'" src="http://qxprice.360buyimg.com/gp1000567419,2.png">
          </div>
        </li>

        <li class="fore"><span>10</span><div class="ulimg"><a href="http://www.qianxun.com/product/378059.html" target="_blank" title=""><img src="http://img14.360buyimg.com/n2/4690/6608d598-9f7b-4270-b38a-1c3901dfa72b.jpg" width="50" height="50" alt="" onerror="this.src='http://misc.qianxun.com/images/none100.gif'"></a></div><div class="name"><a href="http://www.qianxun.com/product/378059.html" target="_blank" title="">FIRSTIME孚仕机械男表7106MY</a></div>
          <div class="price">
            <img onerror="this.src='http://misc.qianxun.com/images/no2.gif'" src="http://qxprice.360buyimg.com/gp378059,2.png">
          </div>
        </li>

      </ul>
    </div>
  </div>
  <div class="listright" >
    <div class ="introduce">
      <h2><span class="fr">共1104个商品</span></h2>
      <div style="display:block" class="block">
        <ul>
          <% @products.each do |product| %>
          <li>
                              <a href= <%= product_path(product) %> target="_blank" title="">
                    <%= image_tag product.avatar(:normal)  %>
                  </a>
                  <h5 class="c-name">
                  <%= link_to product.title, product %>
                  </h5>

            <p class="btns">
              <%= link_to "咨询", message_new_path(product), :id=>"InitCartUrl", :class=>"btn-buy" %>
              <%= link_to "购买", order_new_path(product), :id=>"InitCartUrl", :class=>"btn-buy" %>
            </p>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>



  <%= link_to "new product" , new_product_path%>
  <%= link_to "back" , root_path %>
</div>

app/views/products/new.html.erb
<div class="content">

<h1>发布新产品</h1>
<div style="text-align: center">
  <%= semantic_form_for(@product, :html => { :multipart => true }) do |f|%>
  <div>
  <%= f.input :title, :label=> "标题:   ", :wrapper_html => { :style => "margin:10px;" } %>
   
    <%= f.input :tel, :label => "电话:   ", :wrapper_html => { :style => "margin:10px;" } %>
    <%= f.input :avatar, :label => "图片:   ", :wrapper_html => { :style => "margin:10px;" } %>
  </div>
  描述:

  <%= f.input :description, :label => false,%>
    <%= f.buttons do %>
      <%= f.commit_button %>
    <% end %>
  <% end %>
  </div>
<%= link_to "back" , products_path %>
  </div>

app/views/products/show.html.erb
<div class="content">
  <div class="head_extra">
    <div class="preview">
      <div id="preview"><%= image_tag @product.avatar(:normal) %></div>

    </div>
    <div class="summary">
      <h1><%= @product.title %></h1>
      <ul style="z-index:10;position:relative;">
        <li><span class="fl"><span>库&nbsp;&nbsp;&nbsp;&nbsp;存：现货</span></span></li>
        <li><span class="fl"><span><strong>已销售:</strong>10000吨</span></span></li>
      </ul>
      
      <div class="choose">
        <h2>产品详情:</h2>
        <div style="padding:12px; line-height: 25px;"><%= @product.description %></div>
      </div>
      <%= link_to "购买", order_new_path(@product), :id=>"InitCartUrl", :class=>"shopping" %>
      <%= link_to "咨询", message_new_path(@product), :id=>"", :class=>"btn-coll addpage" %>
              
    </div>

  </div>
</div>