config/routes.rb
Cnmtsc::Application.routes.draw do

  get "messages/new/:id" => "messages#new", :as => :message_new
  post "messages" => "messages#create", :as => :messages

  get "orders/new/:id" => "orders#new", :as => :order_new
  post "orders" => "orders#create", :as => :orders
  match "profile" => "homes#profile", :as => :profile

  get "homes/index"
  root :to => "homes#index"
  resource :user_session
  match "login" => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'register' => "users#new", :as => :register
  resources :news, :only => [:show,:index]
  resources :products, :only => [:show, :index, :new, :create]
  resources :users, :only => [:new, :create]

  namespace :admin do
    root :to => "main#index"
    
    resources :users do
      collection do
        get "change_password"
        put "update_password"
      end
    end
    resources :news
    resources :products
    match "messages" => "messages#index", :as => "messages"
  end

end

app/views/admin/shared/_main_nav.html.erb
<ul id="main-nav">
	<%= main_nav(:home, {}) do %>
		<h3><%= link_to "控制面板", admin_root_path(), :class => "no-submenu" %></h3>
	<% end %>
	
	<%= main_nav(:content, {}) do %>
		<h3>内容管理</h3>
		<ul>
			<%= sec_nav :news do %><%= link_to "新闻管理", admin_news_index_path() %><% end %>
                        <%= sec_nav :products do %><%= link_to "产品管理", admin_products_path() %><% end %>
                        <%= sec_nav :messages do %><%= link_to "消息管理", admin_messages_path() %><% end %>

		</ul>
	<% end %>
	
	<%= main_nav(:system, {}) do %>
		<h3>系统管理</h3>
		<ul>
			<%= sec_nav :users do %><%= link_to "系统用户管理", admin_users_path() %><% end %>
			<%= sec_nav :password do %><%= link_to "当前用户密码修改", change_password_admin_users_path() %><% end %>
			<%= sec_nav :bstar do %><%= link_to "前往Ekhlas前台", root_path(), :target => "_blank" %><% end %>
		</ul>
	<% end %>
</ul>

app/views/admin/shared/_pagination.html.erb
<%- if pagination.total_pages <= 1 -%>
<%- else -%>
<%= will_paginate pagination, :previous_label => "上一页", :next_label => "下一页" %>
<% end -%>

app/views/admin/shared/_sidebar.html.erb
<div id="sidebar-wrapper">

	<a href="<%= admin_root_path() %>"><h1 id="sidebar-title"></h1></a>

	<div id="profile-links">
		您好, <a href="#" title="Edit your profile"><%= current_user.login %></a>, you have <a href="#messages" rel="modal" title="3 Messages"><%= Message.count %> Messages</a><br />
		<br />
		<%= link_to "前往前台", root_path(), :title => "前往川南煤炭市场网前台" %> | <%= link_to "注销", user_session_path(), :method => :delete, :confirm => "确定要注销吗?" %>
	</div>        

	<%= render "admin/shared/main_nav" %>

	<div id="messages" style="display: none"></div>

</div>